plugins {
    id 'java-library'
}

dependencies {
    api 'dnsjava:dnsjava:3.6.3'
    implementation 'com.google.guava:guava:33.4.8-jre'
    implementation 'org.slf4j:slf4j-api:2.0.17'

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.18.0'
    testImplementation 'org.assertj:assertj-core:3.27.3'
}
